// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddbookduplTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addbookdupl() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("addBook-category")).click();
    driver.findElement(By.id("addBook-category")).sendKeys("fiction");
    driver.findElement(By.id("addBook-id")).click();
    driver.findElement(By.id("addBook-id")).sendKeys("hall001");
    driver.findElement(By.id("addBook-title")).click();
    driver.findElement(By.id("addBook-title")).sendKeys("slenium tests");
    driver.findElement(By.id("addBook-authors")).click();
    driver.findElement(By.id("addBook-authors")).sendKeys("dave");
    driver.findElement(By.id("longDescription")).click();
    driver.findElement(By.id("longDescription")).sendKeys("wwdqdq");
    driver.findElement(By.id("cost")).click();
    driver.findElement(By.id("cost")).sendKeys("15");
    driver.findElement(By.name("addBook")).click();
    driver.findElement(By.cssSelector("h2")).click();
    driver.findElement(By.cssSelector(".content")).click();
  }
}
